### ISSUE TITLE
Missing instructions for setting up Admin

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-run-anthos-reference-web-app#117] opened 2020-07-21 18:51 UTC
**Actual**
instructions:
```
cd webui
npm run init-admin <email>
```

user.ts:  
can't find 'credentials'
```
require('../credentials')
```
This logic isn't correct
```
if (userRecord.customClaims && userRecord.customClaims.role !== role)
```

*Updates*
instructions:
```
cd webui
npm i # or maybe just cypress
npm run init-admin <email>
```

user.ts:
```
if (!userRecord.customClaims || userRecord.customClaims!.role !== role)
```

**Comment by adamdkane** [comment] 2020-07-23 15:07
@zsxking is this a dupe of #114 ? if so can you please de-dupe it.

**Closed** 2020-07-23 20:04 UTC
